package org.example;

//    easy #counter #string
//    https://leetcode.com/problems/find-the-difference
//    You are given two strings s and t.
//    String t is generated by random shuffling string s and then add one more letter at a random position.
//    Return the letter that was added to t.
//    Example 1:
//    Input: s = "abcd", t = "abcde"
//    Output: "e"
//    Explanation: 'e' is the letter that was added.
//    Example 2:
//    Input: s = "", t = "y"
//    Output: "y"
public class SolutionDay41Second {
    public static char findTheDifference(String s, String t) {
        int n = s.length();
        int[] counter = new int[26];
        char[] cs = s.toCharArray();
        char[] ct = t.toCharArray();
        for (int i = 0; i < n; i++) {
            counter[cs[i] - 'a']++;
            counter[ct[i] - 'a']--;
        }
        counter[ct[n] - 'a']--;
        char ans = '@';
        for (int i = 0; i < 26; i++) {
            if (counter[i] != 0) {
                ans = (char) (i + 'a');
                break;
            }
        }
        return ans;
    }
}
